### ISSUE TITLE
Chapter 5. Data Engineering | Error on run manifests/kfdef/ml-platform.yaml 

### ISSUE THREAD

**Issue by webmakaka** [PacktPublishing/Machine-Learning-on-Kubernetes#6]
Hello!

After i run

```
$ kubectl create -f - --namespace ml-workshop manifests/kfdef/ml-platform.yaml
```

I am getting 

![pic1](https://user-images.githubusercontent.com/10372159/184975179-b9d1123d-8f9a-448f-9735-7e2427a58edc.png)

![pic2](https://user-images.githubusercontent.com/10372159/184975197-5916aeee-ecc0-4564-9018-0f0a1af7e4e0.png)

![pic3](https://user-images.githubusercontent.com/10372159/184975235-6922fda3-e4b8-4f17-b946-eb182c2d5baa.png)

Full log if needed

```python
$ kubectl logs start-spark-cluster.3f3abca9fc804b3e9ade7c47afab0a04 --namespace ml-workshop
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18688  100 18688    0     0   214k      0 --:--:-- --:--:-- --:--:--  214k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1282  100  1282    0     0  16227      0 --:--:-- --:--:-- --:--:-- 16227
Requirement already satisfied: packaging in /opt/app-root/lib/python3.8/site-packages (21.0)
Requirement already satisfied: pyparsing>=2.0.2 in /opt/app-root/lib/python3.8/site-packages (from packaging) (2.4.7)
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/opt/app-root/bin/python3 -m pip install --upgrade pip' command.
[I 19:47:05.009] 'jhuser-0623-02-spark-0623202840':'start-spark-cluster' - starting operation 
[I 19:47:05.009] 'jhuser-0623-02-spark-0623202840':'start-spark-cluster' - Installing packages 
[I 19:47:05.010] Package not found. Installing ipykernel package with version 5.3.0...
[I 19:47:05.010] Package not found. Installing ipython package with version 7.15.0...
[I 19:47:05.010] Package not found. Installing ipython-genutils package with version 0.2.0...
[I 19:47:05.010] Package not found. Installing jupyter-client package with version 6.1.6...
[I 19:47:05.010] Package not found. Installing jupyter-core package with version 4.6.3...
[I 19:47:05.010] Newer minio package with version 6.0.2 already installed. Skipping...
[I 19:47:05.010] Package not found. Installing nbclient package with version 0.4.1...
[I 19:47:05.010] Package not found. Installing nbconvert package with version 5.6.1...
[I 19:47:05.010] Package not found. Installing nbformat package with version 5.0.7...
[I 19:47:05.010] Package not found. Installing papermill package with version 2.1.2...
[I 19:47:05.010] Package not found. Installing pyzmq package with version 19.0.1...
[I 19:47:05.010] Package not found. Installing prompt-toolkit package with version 3.0.5...
[I 19:47:05.010] Newer requests package with version 2.26.0 already installed. Skipping...
[I 19:47:05.010] Package not found. Installing tornado package with version 6.0.4...
[I 19:47:05.010] Package not found. Installing traitlets package with version 4.3.3...
[I 19:47:05.010] Newer urllib3 package with version 1.26.7 already installed. Skipping...
Collecting ipykernel==5.3.0
  Downloading ipykernel-5.3.0-py3-none-any.whl (119 kB)
Collecting ipython==7.15.0
  Downloading ipython-7.15.0-py3-none-any.whl (783 kB)
Collecting ipython-genutils==0.2.0
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting jupyter-client==6.1.6
  Downloading jupyter_client-6.1.6-py3-none-any.whl (108 kB)
Collecting jupyter-core==4.6.3
  Downloading jupyter_core-4.6.3-py2.py3-none-any.whl (83 kB)
Collecting nbclient==0.4.1
  Downloading nbclient-0.4.1-py3-none-any.whl (65 kB)
Collecting nbconvert==5.6.1
  Downloading nbconvert-5.6.1-py2.py3-none-any.whl (455 kB)
Collecting nbformat==5.0.7
  Downloading nbformat-5.0.7-py3-none-any.whl (170 kB)
Collecting papermill==2.1.2
  Downloading papermill-2.1.2-py3-none-any.whl (32 kB)
Collecting pyzmq==19.0.1
  Downloading pyzmq-19.0.1-cp38-cp38-manylinux1_x86_64.whl (1.1 MB)
Collecting prompt-toolkit==3.0.5
  Downloading prompt_toolkit-3.0.5-py3-none-any.whl (351 kB)
Collecting tornado==6.0.4
  Downloading tornado-6.0.4.tar.gz (496 kB)
Collecting traitlets==4.3.3
  Downloading traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
Collecting backcall
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: setuptools>=18.5 in /opt/app-root/lib/python3.8/site-packages (from ipython==7.15.0) (41.6.0)
Collecting pygments
  Downloading Pygments-2.13.0-py3-none-any.whl (1.1 MB)
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting pexpect
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting pickleshare
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting jedi>=0.10
  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
Requirement already satisfied: python-dateutil>=2.1 in /opt/app-root/lib/python3.8/site-packages (from jupyter-client==6.1.6) (2.8.2)
Collecting async-generator
  Downloading async_generator-1.10-py3-none-any.whl (18 kB)
Collecting nest-asyncio
  Downloading nest_asyncio-1.5.5-py3-none-any.whl (5.2 kB)
Requirement already satisfied: jinja2>=2.4 in /opt/app-root/lib/python3.8/site-packages (from nbconvert==5.6.1) (3.0.1)
Collecting mistune<2,>=0.8.1
  Downloading mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: entrypoints>=0.2.2 in /opt/app-root/lib/python3.8/site-packages (from nbconvert==5.6.1) (0.3)
Collecting defusedxml
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting testpath
  Downloading testpath-0.6.0-py3-none-any.whl (83 kB)
Collecting pandocfilters>=1.4.1
  Downloading pandocfilters-1.5.0-py2.py3-none-any.whl (8.7 kB)
Collecting bleach
  Downloading bleach-5.0.1-py3-none-any.whl (160 kB)
Collecting jsonschema!=2.5.0,>=2.4
  Downloading jsonschema-4.10.0-py3-none-any.whl (80 kB)
Collecting tenacity
  Downloading tenacity-8.0.1-py3-none-any.whl (24 kB)
Collecting ansiwrap
  Downloading ansiwrap-0.8.4-py2.py3-none-any.whl (8.5 kB)
Requirement already satisfied: pyyaml in /opt/app-root/lib/python3.8/site-packages (from papermill==2.1.2) (5.4.1)
Requirement already satisfied: requests in /opt/app-root/lib/python3.8/site-packages (from papermill==2.1.2) (2.26.0)
Collecting tqdm>=4.32.2
  Downloading tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Requirement already satisfied: click in /opt/app-root/lib/python3.8/site-packages (from papermill==2.1.2) (8.0.1)
Collecting black
  Downloading black-22.6.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Requirement already satisfied: six in /opt/app-root/lib/python3.8/site-packages (from traitlets==4.3.3) (1.16.0)
Collecting parso<0.9.0,>=0.8.0
  Downloading parso-0.8.3-py2.py3-none-any.whl (100 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/app-root/lib/python3.8/site-packages (from jinja2>=2.4->nbconvert==5.6.1) (2.0.1)
Collecting attrs>=17.4.0
  Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting pkgutil-resolve-name>=1.3.10
  Downloading pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (119 kB)
Collecting importlib-resources>=1.4.0
  Downloading importlib_resources-5.9.0-py3-none-any.whl (33 kB)
Requirement already satisfied: zipp>=3.1.0 in /opt/app-root/lib/python3.8/site-packages (from importlib-resources>=1.4.0->jsonschema!=2.5.0,>=2.4->nbformat==5.0.7) (3.5.0)
Collecting textwrap3>=0.9.2
  Downloading textwrap3-0.9.2-py2.py3-none-any.whl (12 kB)
Collecting tomli>=1.1.0
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting mypy-extensions>=0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting pathspec>=0.9.0
  Downloading pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: typing-extensions>=3.10.0.0 in /opt/app-root/lib/python3.8/site-packages (from black->papermill==2.1.2) (3.10.0.2)
Collecting platformdirs>=2
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: certifi>=2017.4.17 in /opt/app-root/lib/python3.8/site-packages (from requests->papermill==2.1.2) (2021.5.30)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/app-root/lib/python3.8/site-packages (from requests->papermill==2.1.2) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/app-root/lib/python3.8/site-packages (from requests->papermill==2.1.2) (2.0.6)
Requirement already satisfied: idna<4,>=2.5 in /opt/app-root/lib/python3.8/site-packages (from requests->papermill==2.1.2) (3.2)
Building wheels for collected packages: tornado
  Building wheel for tornado (setup.py): started
  Building wheel for tornado (setup.py): finished with status 'done'
  Created wheel for tornado: filename=tornado-6.0.4-cp38-cp38-linux_x86_64.whl size=428150 sha256=69de556337567b40733cd63882ecad9117573709e377f5e8dc6defdb4e34fdba
  Stored in directory: /tmp/pip-ephem-wheel-cache-h9e_6z1g/wheels/88/79/e5/598ba17e85eccf2626eab62e4ee8452895636cd542650d450d
Successfully built tornado
Installing collected packages: ipython-genutils, decorator, traitlets, pyrsistent, pkgutil-resolve-name, importlib-resources, attrs, wcwidth, tornado, pyzmq, ptyprocess, parso, jupyter-core, jsonschema, webencodings, tomli, textwrap3, pygments, prompt-toolkit, platformdirs, pickleshare, pexpect, pathspec, nest-asyncio, nbformat, mypy-extensions, jupyter-client, jedi, backcall, async-generator, tqdm, testpath, tenacity, pandocfilters, nbclient, mistune, ipython, defusedxml, bleach, black, ansiwrap, papermill, nbconvert, ipykernel
Successfully installed ansiwrap-0.8.4 async-generator-1.10 attrs-22.1.0 backcall-0.2.0 black-22.6.0 bleach-5.0.1 decorator-5.1.1 defusedxml-0.7.1 importlib-resources-5.9.0 ipykernel-5.3.0 ipython-7.15.0 ipython-genutils-0.2.0 jedi-0.18.1 jsonschema-4.10.0 jupyter-client-6.1.6 jupyter-core-4.6.3 mistune-0.8.4 mypy-extensions-0.4.3 nbclient-0.4.1 nbconvert-5.6.1 nbformat-5.0.7 nest-asyncio-1.5.5 pandocfilters-1.5.0 papermill-2.1.2 parso-0.8.3 pathspec-0.9.0 pexpect-4.8.0 pickleshare-0.7.5 pkgutil-resolve-name-1.3.10 platformdirs-2.5.2 prompt-toolkit-3.0.5 ptyprocess-0.7.0 pygments-2.13.0 pyrsistent-0.18.1 pyzmq-19.0.1 tenacity-8.0.1 testpath-0.6.0 textwrap3-0.9.2 tomli-2.0.1 tornado-6.0.4 tqdm-4.64.0 traitlets-4.3.3 wcwidth-0.2.5 webencodings-0.5.1
WARNING: You are using pip version 21.2.4; however, version 22.2.2 is available.
You should consider upgrading via the '/opt/app-root/bin/python3 -m pip install --upgrade pip' command.
absl-py==0.14.1
alembic==1.4.1
ansiwrap==0.8.4
astunparse==1.6.3
async-generator==1.10
attrs==22.1.0
backcall==0.2.0
bcrypt==3.2.0
black==22.6.0
bleach==5.0.1
boto3==1.18.49
botocore==1.21.49
cachetools==4.2.4
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.6
click==8.0.1
cloudpickle==2.0.0
configparser==5.0.2
cryptography==3.4.8
databricks-cli==0.15.0
decorator==5.1.1
defusedxml==0.7.1
docker==5.0.2
entrypoints==0.3
Flask==2.0.1
flatbuffers==2.0
gast==0.4.0
gitdb==4.0.7
GitPython==3.1.24
google-auth==2.3.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
greenlet==1.1.1
grpcio==1.41.0
gunicorn==20.1.0
h5py==3.4.0
idna==3.2
importlib-metadata==4.8.1
importlib-resources==5.9.0
ipykernel==5.3.0
ipython==7.15.0
ipython-genutils==0.2.0
itsdangerous==2.0.1
jedi==0.18.1
Jinja2==3.0.1
jmespath==0.10.0
joblib==1.0.1
jsonschema==4.10.0
jupyter-client==6.1.6
jupyter-core==4.6.3
keras-nightly==2.7.0.dev2021100607
Keras-Preprocessing==1.1.2
libclang==12.0.0
Mako==1.1.5
Markdown==3.3.4
MarkupSafe==2.0.1
minio==6.0.2
mistune==0.8.4
mlflow==1.20.2
mypy-extensions==0.4.3
nbclient==0.4.1
nbconvert==5.6.1
nbformat==5.0.7
nest-asyncio==1.5.5
numpy==1.21.2
oauthlib==3.1.1
openshift-client==1.0.13
opt-einsum==3.3.0
packaging==21.0
pandas==1.3.3
pandocfilters==1.5.0
papermill==2.1.2
paramiko==2.7.2
parso==0.8.3
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
pkgutil_resolve_name==1.3.10
platformdirs==2.5.2
prometheus-client==0.11.0
prometheus-flask-exporter==0.18.2
prompt-toolkit==3.0.5
protobuf==3.18.0
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
Pygments==2.13.0
PyNaCl==1.4.0
pyparsing==2.4.7
pyrsistent==0.18.1
python-dateutil==2.8.2
python-editor==1.0.4
pytz==2021.1
PyYAML==5.4.1
pyzmq==19.0.1
querystring-parser==1.2.4
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.7.2
s3transfer==0.5.0
scikit-learn==0.24.2
scipy==1.7.1
six==1.16.0
smmap==4.0.0
SQLAlchemy==1.4.25
sqlparse==0.4.2
tabulate==0.8.9
tb-nightly==2.7.0a20211013
tenacity==8.0.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow-io-gcs-filesystem==0.21.0
termcolor==1.1.0
testpath==0.6.0
textwrap3==0.9.2
tf-estimator-nightly==2.7.0.dev2021092408
tf-nightly==2.8.0.dev20211005
threadpoolctl==2.2.0
tomli==2.0.1
tornado==6.0.4
tqdm==4.64.0
traitlets==4.3.3
typing-extensions==3.10.0.2
urllib3==1.26.7
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.2.1
Werkzeug==2.0.1
wrapt==1.13.2
zipp==3.5.0
[I 19:47:15.943] 'jhuser-0623-02-spark-0623202840':'start-spark-cluster' - Packages installed (10.934 secs)
[I 19:47:16.002] 'jhuser-0623-02-spark-0623202840':'start-spark-cluster' - processing dependencies 
Traceback (most recent call last):
  File "bootstrapper.py", line 430, in <module>
    main()
  File "bootstrapper.py", line 421, in main
    file_op.process_dependencies()
  File "bootstrapper.py", line 96, in process_dependencies
    self.get_file_from_object_storage(archive_file)
  File "bootstrapper.py", line 144, in get_file_from_object_storage
    self.cos_client.fget_object(bucket_name=self.cos_bucket,
  File "/opt/app-root/lib64/python3.8/site-packages/minio/api.py", line 787, in fget_object
    stat = self.stat_object(
  File "/opt/app-root/lib64/python3.8/site-packages/minio/api.py", line 1195, in stat_object
    response = self._url_open(
  File "/opt/app-root/lib64/python3.8/site-packages/minio/api.py", line 2226, in _url_open
    raise ResponseError(response,
minio.error.NoSuchKey: NoSuchKey: message: The specified key does not exist.

```

What are the problems?
How to fix it? Thanks.

**Comment by mastash3ff** [comment]
I had the same errors. You will run across more errors eventually like accessing MLFlow through the ingress IP which destroy following along in the book.

**Comment by webmakaka** [comment]
I see here an error

```
minio.error.NoSuchKey: NoSuchKey: message: The specified key does not exist.
```

I just do not know where i should specify it.

**Comment by webmakaka** [comment]
We install

minio==6.0.2

And when we run minio/api.py we have and error on line 787

But where is the starting point for running ocp-deploy container?

**Comment by webmakaka** [comment]
To avoid this behaviour, need create an empty github repo with branch main.
And replace in file manifests/kfdef/ml-platform.yaml 

```
          - name: DAG_REPO
            value: 'https://github.com/airflow-dags/dags/'
```

on

```
          - name: DAG_REPO
            value: 'your-created-repo-for-dags'
```


The result is 

```
$ kubectl get pods -n ml-workshop
NAME                                           READY   STATUS      RESTARTS        AGE
app-aflow-airflow-scheduler-6ccc679fc6-6k9kv   2/2     Running     0               17m
app-aflow-airflow-web-55767cd99d-x9kh7         2/2     Running     0               9m41s
app-aflow-airflow-worker-0                     2/2     Running     1 (8m38s ago)   17m
app-aflow-postgresql-0                         1/1     Running     0               17m
app-aflow-redis-master-0                       1/1     Running     0               17m
flightsdatadb-0                                1/1     Running     0               15m
grafana-56594fd448-c76qd                       1/1     Running     0               17m
jupyterhub-6cff7d6cc5-62snc                    1/1     Running     0               17m
jupyterhub-db-0                                1/1     Running     0               17m
minio-ml-workshop-7fcc5dfd8-m57lv              1/1     Running     0               17m
minio-ml-workshop-lbfh5                        0/1     Completed   2               17m
mlflow-5fb4cb5d5d-89v74                        2/2     Running     0               17m
mlflow-db-0                                    1/1     Running     1 (16m ago)     17m
prometheus-odh-monitoring-0                    2/2     Running     0               13m
prometheus-operator-7869664bcc-f42d2           1/1     Running     0               15m
seldon-controller-manager-c5f59c56d-2rcc6      1/1     Running     0               17m
spark-operator-6bc4f8f5f8-rs2mk                1/1     Running     0               17m

```
